<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>addMultipleItmsFrmExcel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-22T14:31:31</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>86b3320b-ff46-4909-b32a-6485ffe8aa3a</testSuiteGuid>
   <testCaseLink>
      <guid>374a67ce-71da-43b1-a695-cffc2c646cec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>859c5cde-570f-49c6-bcda-b852fa8481b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3cf65b-75e3-435d-a3e5-2f28fa0335d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ab0251-c608-4888-938a-3c4717e184bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c952341-718b-4f7d-ae34-cdd126324b69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addItem</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>70a3838c-dfcc-4f09-a2d0-135cebe02bc8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/stockItems</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>70a3838c-dfcc-4f09-a2d0-135cebe02bc8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>3b96edcf-c5df-4321-b7f6-db27774a68e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>70a3838c-dfcc-4f09-a2d0-135cebe02bc8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>7c06561e-df29-46b2-b817-5f4ddf5e50a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>70a3838c-dfcc-4f09-a2d0-135cebe02bc8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>supplier</value>
         <variableId>8b6d0ca6-2d79-4da7-a199-8d986486f852</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
